name: Rollback Staging

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ROLE_TO_ASSUME: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/staging-github-oidc

  # Backend remoto de Terraform (defínelos en Environment "staging")
  TF_BACKEND_BUCKET: ${{ secrets.AWS_ACCOUNT_ID }}-${{ vars.GH_REPO }}-staging
  TF_BACKEND_KEY: ${{ vars.GH_REPO }}/staging/terraform.tfstate 
  TF_BACKEND_DDB_TABLE: tf-locks-${{ vars.GH_REPO }}-staging

  # Variables Terraform (mismo set que deploy)
  TF_VAR_gh_owner: ${{ vars.GH_OWNER }}
  TF_VAR_gh_repo:  ${{ vars.GH_REPO }}
  TF_VAR_name_prefix: staging
  TF_VAR_tf_backend_bucket: ${{ secrets.AWS_ACCOUNT_ID }}-${{ vars.GH_REPO }}-staging
  TF_VAR_tf_backend_ddb_table: tf-locks-${{ vars.GH_REPO }}-staging

jobs:
  destroy:
    environment: staging
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      # 1) Asegura S3/DynamoDB (maneja us-east-1 sin LocationConstraint)
      - name: Ensure S3 bucket and DynamoDB table for tfstate
        shell: bash
        run: |
          set -euo pipefail
          echo "Region: $AWS_REGION"
          echo "Bucket: $TF_BACKEND_BUCKET"
          echo "DDB   : $TF_BACKEND_DDB_TABLE"

          if aws s3api head-bucket --bucket "$TF_BACKEND_BUCKET" 2>/dev/null; then
            echo "Bucket exists"
          else
            if [ "$AWS_REGION" = "us-east-1" ]; then
              aws s3api create-bucket --bucket "$TF_BACKEND_BUCKET"
            else
              aws s3api create-bucket \
                --bucket "$TF_BACKEND_BUCKET" \
                --region "$AWS_REGION" \
                --create-bucket-configuration LocationConstraint="$AWS_REGION"
            fi
          fi

          aws s3api put-bucket-versioning \
            --bucket "$TF_BACKEND_BUCKET" \
            --versioning-configuration Status=Enabled

          aws s3api put-bucket-encryption \
            --bucket "$TF_BACKEND_BUCKET" \
            --server-side-encryption-configuration '{
              "Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]
            }'

          if aws dynamodb describe-table --table-name "$TF_BACKEND_DDB_TABLE" >/dev/null 2>&1; then
            echo "DynamoDB table exists"
          else
            aws dynamodb create-table \
              --table-name "$TF_BACKEND_DDB_TABLE" \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST
          fi

      # 2) Verifica acceso (ya existe bucket/tabla)
      - name: Check backend access
        shell: bash
        run: |
          set -euo pipefail
          echo "Testing S3/DynamoDB access..."
          aws s3 ls "s3://${TF_BACKEND_BUCKET}" >/dev/null
          aws dynamodb describe-table --table-name "${TF_BACKEND_DDB_TABLE}" >/dev/null

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # 3) Init con backend remoto (y migra state local si existiera)
      - name: Terraform Init 
        working-directory: ./infrastructure
        shell: bash
        run: |
          set -euo pipefail

          echo "Checking if remote state object exists in S3..."
          if aws s3api head-object --bucket "${TF_BACKEND_BUCKET}" --key "${TF_BACKEND_KEY}" >/dev/null 2>&1; then
            echo "Remote state FOUND → using -reconfigure"
            INIT_FLAGS="-reconfigure"
          else
            if [ -f "terraform.tfstate" ]; then
              echo "Local state FOUND and remote state MISSING → using -migrate-state"
              INIT_FLAGS="-migrate-state"
            else
              echo "No local state and no remote state → plain init (no special flags)"
              INIT_FLAGS=""
            fi
          fi

          terraform init -input=false ${INIT_FLAGS} \
            -backend-config="bucket=${TF_BACKEND_BUCKET}" \
            -backend-config="key=${TF_BACKEND_KEY}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="dynamodb_table=${TF_BACKEND_DDB_TABLE}" \
            -backend-config="encrypt=true"

      # 4) (Opcional) Inspecciona el state para confirmar recursos
      - name: Show state (debug)
        working-directory: ./infrastructure
        run: |
          echo "Workspace: $(terraform workspace show)"
          terraform state list || true

      # 5) Destroy real con el state remoto
      - name: Destroy
        working-directory: ./infrastructure
        run: terraform destroy -auto-approve -input=false
